ru_en = {
    "Неверный логин или пароль": "Wrong login or password",
    "Вы вошли в аккаунт": "You are signed in",
    "Аккаунт на эту почту уже зарегистрирован":
        "An account for this email has already been registered",
    "Поздравляем, Вы создали аккаунт!": "Congratulations, you have created an account!",
    "Добавить": "Add",
    "Доход": "Income",
    "Расход": "Expense",
    "Расходов": "Expenses",
    "Доходов": "Incomes",
    "Доходам": "Incomes",
    "Расходам": "Expenses",
    "Категории": "Categories",
    "Панель управления": "Control Panel",
    "Данные изменены": "Data changed",
    "Счета": "Bank accounts",
    'Новая категория': 'New category',
    'Новый счет': 'New bank account',
    "Аналитика": "Analytics",
    "Средств недостаточно": "There are not enough funds",
    "Счет с таким названием уже существует": "An account with the same name already exists",
    "Категория с таким названием уже существует": "A category with the same name already exists",


    "Общая сумма": "Total amount",
    "Доходы за месяц": "Incomes per month",
    "Расходы за месяц": "Expenses per month",
    "Название счета": "Name of bank account",
    "Дата": "Date,",
    'Сумма': 'Amount',
    'Комментарий': 'Comment',
    "Добавить доход": "Add income",
    "Категория": "Category",
    "Счет": "Bank account",
    'Добавление/Изменение категории': 'Add/Change category of',
    "Название категории": "Name of category",
    "Категории доходов и расходов": "Categories of income and expenses",
    'Тип': 'Type',
    'Описание': 'Description',
    'Название': "Name",
    'Добавление/Изменение счета': 'Add/Change bank account',
    'Добавить/Изменить': 'Add/Edit',
    'По': 'By',
    "От": 'From',
    'До (включительно)': 'To (inclusive)',
    "Построить график": "Build a graph",
    "Упс! Вы ввели данные в неверном формате!":
        "Oops! You entered data in the wrong format!",
    "К сожалению мы не можем выполнить запрос из-за некорректных введенных данных.":
        "Unfortunately, we are unable to complete your request due to incorrect data entered.",
    "Вернуться назад": "Come back",
    "Ой! Страница не найдена!": "Oh! Page not found!",
    "К сожалению мы не можем найти запрошенную вами страницу. Возможно, вы неправильно ввели адрес.":
        "Unfortunately, we cannot find the page you requested. You may have entered the address "
        "incorrectly.",
    'Выход': "Logout",
    "Категорию расходов": "Category of expenses",
    "Категорию доходов": "Category of incomes",
    "Экспорт данных в xlsx": "Export data to xlsx",
    "Экспорт данных в csv (zip)": "Export data to csv (zip)",
    '': '?lang=en',
    "Почта": "Email",
    "Пароль": "Password",
    'Запомнить меня': "Remember me",
    'Войти': 'Login',
    'ФИО': 'Full name',
    'Зарегистрироваться': 'Register',
    'Режим': 'Mode',
    "Создать аккаунт WebFinUp": "Create a WebFinUp account",
    "Войти в аккаунт WebFinUp": "Login to your WebFinUp account"
}


