"""Initial migration.

Revision ID: d516ecc63f08
Revises: 
Create Date: 2023-12-22 14:00:03.911670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd516ecc63f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('username_email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username_email')
    )
    op.create_table('bank_accounts',
    sa.Column('id_bank_account', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('current_sum', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_bank_account')
    )
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('deposit_categories',
    sa.Column('id_deposit_category', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_deposit_category')
    )
    op.create_table('deposits',
    sa.Column('id_deposit', sa.Integer(), nullable=False),
    sa.Column('id_deposit_category', sa.Integer(), nullable=True),
    sa.Column('id_bank_account', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('date_time_add', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_bank_account'], ['bank_accounts.id_bank_account'], ),
    sa.ForeignKeyConstraint(['id_deposit_category'], ['deposit_categories.id_deposit_category'], ),
    sa.PrimaryKeyConstraint('id_deposit')
    )
    op.create_table('purchases',
    sa.Column('id_purchase', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_bank_account', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('date_time_add', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_bank_account'], ['bank_accounts.id_bank_account'], ),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.PrimaryKeyConstraint('id_purchase')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('deposits')
    op.drop_table('deposit_categories')
    op.drop_table('categories')
    op.drop_table('bank_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
